CREATE TABLE `registrations` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`confirmation_code` text NOT NULL,
	`title` text DEFAULT '' NOT NULL,
	`first_name` text NOT NULL,
	`last_name` text NOT NULL,
	`email` text NOT NULL,
	`phone` text NOT NULL,
	`country` text NOT NULL,
	`city` text DEFAULT '' NOT NULL,
	`church_organisation` text DEFAULT '' NOT NULL,
	`role` text DEFAULT '' NOT NULL,
	`ticket_type` text NOT NULL,
	`attendance_days` text NOT NULL,
	`accommodation` text NOT NULL,
	`room_type` text DEFAULT '' NOT NULL,
	`check_in` text DEFAULT '' NOT NULL,
	`check_out` text DEFAULT '' NOT NULL,
	`airport_transfer` text NOT NULL,
	`arrival_airport` text DEFAULT '' NOT NULL,
	`arrival_flight` text DEFAULT '' NOT NULL,
	`arrival_datetime` text DEFAULT '' NOT NULL,
	`departure_flight` text DEFAULT '' NOT NULL,
	`departure_datetime` text DEFAULT '' NOT NULL,
	`hotel_shuttle` text NOT NULL,
	`meal_preference` text NOT NULL,
	`dietary_needs` text DEFAULT '' NOT NULL,
	`accessibility_needs` text DEFAULT '' NOT NULL,
	`emergency_name` text DEFAULT '' NOT NULL,
	`emergency_phone` text DEFAULT '' NOT NULL,
	`payment_status` text DEFAULT 'pending' NOT NULL,
	`notes` text DEFAULT '' NOT NULL,
	`consent` integer NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `registrations_confirmation_code_unique` ON `registrations` (`confirmation_code`);